### ISSUE TITLE
pyodbc-3.0.2.win32-py2.6.exe installer for win32 does not appear to work out of the box.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [maximemaher/pyodbc#234]
```
What steps will reproduce the problem?
1. Clean install of Python 2.6
2. Install the pyodbc files
3. try to:"import pydobc"

What is the expected output? What do you see instead?
>>>
ImportError: No module named pyodbc

What version of the product are you using? On what operating system?

Python 2.6 with 3.0.2.win32

Please provide any additional information below.

Installed earlier version and it worked fine.
```

Original issue reported on code.google.com by `halowa...@gmail.com` on 25 Jan 2012 at 11:06

**Comment by GoogleCodeExporter** [comment]
```
Is it possible it installed in a different version of Python, say a 64-bit vs a 
32-bit version?  I've never seen this.

There should be a pyodbc.pyd file in the Python/Libs/site-packages directory.  
Perhaps it is a setuptools related issue.  Do you see any pyodbc files in the 
site-packages directory?
```

Original comment by `mkleehammer` on 25 Jan 2012 at 11:09
- Changed state: **Investigating**

**Comment by GoogleCodeExporter** [comment]
```
Hi,

I have same issue:
>>> import pyodbc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: The specified procedure could not be found.

I have Python 2.6 32-bit installed. My OS is Windows 2008 R2, which is 64-bit.
I have tried to install the version 3.0.5 over Python 2.7 on same computer and 
it worked OK.
I can see the libraries in the D:\Python26\Lib\site-packages\pyodbc.pyd, and 
the D:\Python26\Lib\site-packages\pyodbc-3.0.2-py2.6.egg-info folder.

Version pyodbc-2.1.11.win32-py2.6.exe works fine.
```

Original comment by `ra...@liveperson.com` on 17 Jun 2012 at 7:49

**Comment by GoogleCodeExporter** [comment]
```
I'm having the same trouble.

Trying to import pyodbc with python shell works fine.

But when I try to import it in to my program thats using a diffrent
version of MSVCR90.DLL i get the error:
ImportError: DLL load failed: The specified module could not be found.

The module is in a folder that Im able too import from. 

Since this is depening on a diffrent compliation of VB I suppose.

The only suggestion too solve this problem I found googling whas to recompile
the pyodbc file with the right VB version.
```

Original comment by `sverkerl...@gmail.com` on 6 Feb 2013 at 10:30

**Comment by GoogleCodeExporter** [comment]
```
I am facing exactly same issue.
I downloaded pyodbc-3.0.6.win32-py2.6.exe for my 32 bit laptop.
I have Python2.6 installed already.

When I Go to help and type pyodbc, it gives error. See below:
help> pyodbc
problem in pyodbc - <type 'exceptions.ImportError'>: DLL load failed: The specif
ied procedure could not be found.

If I just type import pyodbc, it gives error too. See below:
>>> import pyodbc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: The specified procedure could not be found.


```

Original comment by `priyanka...@gmail.com` on 20 Mar 2013 at 9:54

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Did anybody solve this? Having the same problem.
```

Original comment by `nameisp...@gmail.com` on 17 Mar 2014 at 5:00

**Comment by GoogleCodeExporter** [comment]
```
I'm having the same problem (as follows):
python 2.6.3 installed (32-bit)
installed pyodbc-3.0.7.win32-py2.6.exe (or even anything above 3.0.x)
import pyodbc results in:
----------
C:\Python26>python
Python 2.6.3 (r263rc1:75186, Oct  2 2009, 20:40:30) [MSC v.1500 32 bit (Intel)] 
on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyodbc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: The specified procedure could not be found.
>>>
----------

pyodbc-2.1.11.win32-py2.6.exe works fine, but I'd like to upgrade to latest 
version, but can't seem to get it working.

OS is Windows 8.1 64-bit.
```

Original comment by `joe.lan...@gmail.com` on 4 Nov 2014 at 7:10
