### ISSUE TITLE
3.0.5 source dist

### ISSUE THREAD

**Issue by GoogleCodeExporter** [maximemaher/pyodbc#272]
```
I cannot find a source distribution for version 3.0.5.

I am trying to make it from a git clone but the version handling in setup.py 
lost me.

Could you provide a source dist for 3.0.5 ?

Also, the last version on pypi is 3.0.3 
(http://pypi.python.org/pypi/pyodbc/3.0.3), and 
http://pypi.python.org/pypi/pyodbc says 'not found()'. It is a bit confusing.


Thanks,

Christophe
```

Original issue reported on code.google.com by `cdevie...@gmail.com` on 20 Jun 2012 at 10:07

**Comment by GoogleCodeExporter** [comment]
```
I'm not sure about google code, but I can tell you how to do it using the 
github.com repository.  You can look at the tags in the repository browser and 
click on the dropdown "branch: master", then choose tags to see the tag names:

1. clone the repository
  git clone https://github.com/mkleehammer/pyodbc.git
2. checkout only the 3.0.5 tag
  git checkout <tag_name> (e.g. 3.0.5 for your source)


From here, you use setup.py to build 3.0.5.  I would suggest using the newest 
version checked into the repo, which I believe is currently 3.1.0.
```

Original comment by `dkleeham...@gmail.com` on 22 Jun 2012 at 9:33

**Comment by GoogleCodeExporter** [comment]
```
Hi,

I did a clone a checkout the 3.0.5 tag, then I run "python setup.py sdist", but 
I get this :

Traceback (most recent call last):
  File "setup.py", line 276, in <module>
    main()
  File "setup.py", line 61, in main
    version_str, version = get_version()
  File "setup.py", line 218, in get_version
    name, numbers = _get_version_git()
  File "setup.py", line 261, in _get_version_git
    branch = re.search(r'\* (\w+)', result).group(1)
AttributeError: 'NoneType' object has no attribute 'group'


It seems from the way the version is handled in setup.py that I cannot build 
the sdist from a tag.

Meanwhile I am using a head version, but having an official source release of 
the latest version on pypi would be nice for users running python 2.5 under 
linux.

Also, did you see the pypi page : http://pypi.python.org/pypi/pyodbc ?

Thanks,

Christophe
```

Original comment by `cdevie...@gmail.com` on 24 Jun 2012 at 11:25

**Comment by GoogleCodeExporter** [comment]
```
Just seen the 3.0.6 release, solving my issue (although I cannot close it).

Thanks,

Christophe
```

Original comment by `cdevie...@gmail.com` on 26 Jun 2012 at 7:22

**Comment by GoogleCodeExporter** [comment]
```
Thanks for notifying us.
```

Original comment by `mkleehammer` on 26 Jun 2012 at 1:24
- Changed state: **Complete**
